### ISSUE TITLE
Add local embedding

### ISSUE THREAD

**Issue by mkrueger12** [Backland-Labs/semantic-cache#3]
- convert the embedding model from openai to a local model

**Comment by mkrueger12** [comment]
Key question: what is the fastest way to use embeddings locally?

**Comment by mkrueger12** [comment]
Move embedding model to own container?

**Comment by Frohrer** [comment]
Good idea for scale. Could also try a separate micro service API.

**Comment by mkrueger12** [comment]
@Frohrer what do you mean by that?

**Comment by Frohrer** [comment]
> @Frohrer what do you mean by that?

If you move the embeddings compute to its own container and make it another microservice, aka its own API endpoint, then that helps with scale. It also helps with provisioning hardware that is specialized to run embeddings locally, only for that workload.

**Comment by mkrueger12** [comment]
Word. I'm gonna do that.
