### ISSUE TITLE
Add JSON validation

### ISSUE THREAD

**Issue by mkrueger12** [Backland-Labs/semantic-cache#8]
- need to explore if necessary, implement if so.

**Comment by sagar2395** [comment]
I would like to work on this issue. @mkrueger12. Please provide more information of requirement.

**Comment by mkrueger12** [comment]
@sagar2395  Thanks for helping out. We need to use the `github.com/go-playground/validator/v10` package to validate in the incoming JSON request data. The two structs that need validating are the request structs in `handlers.go`. Let me know if you have more questions.
